vich_uploader:
    db_driver: orm

    mappings:
       recette_images:
            uri_prefix: /images/recette
            upload_destination: '%kernel.project_dir%/public/images/recette'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above

 